### ISSUE TITLE
Should use Regular Expressions to search for files

### ISSUE THREAD

**Issue by kurogai** [joaroque/sidown#1]
Using an dictionary to search for server files, will slow down the speed of the program. Regular expressions should be used to search for server external files (CSS and Javascript).

Other files like passwords, logs and so on, are okay.

For example:

```
   import re
 
   string = "string to match"
   text = re.match("src=\"([\D0-9]*\")|href=\"([\D0-9]*\")",string)
```

**Comment by joaroquedev** [comment]
You can make a pull request brother. I don't have much experience in
regular expressions

>
